version: "3"

services:
  db:
    image: mariadb:10.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    env_file: .env
    container_name: mariadb    
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
#      - db-data:/var/lib/mysql
      - ./.docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql      
    expose:
      - "3306"
    ports:
      - "3307:3306"
  wordpress:
#    build: ./
    image: wordpress:6.3-php8.1
    env_file: .env    
    container_name: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    volumes:
      - ./:/var/www/html
    ports:
      - "3000:80"

#volumes:
#  db-data:

#networks:
#  default:
#    name: wp-network